services:
  mongodb:
    image: mongo:6.0
    container_name: todo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - todo-mongo-data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/mytodo
      - JWT_SECRET=supersecret_mytodo_jwt_key_2026
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always

volumes:
  todo-mongo-data:
